---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# raldag

<!-- badges: start -->
<!-- badges: end -->

Create and generate data from DAGs.

## Installation
You can install the development version from [GitHub](https://github.com/) with:
``` r
# install.packages("devtools")
devtools::install_github("ianmoran11/raldag")
```

## Example

```{r message = FALSE, warning = FALSE}
rm(list = ls())
library(tidyverse)
library(tidygraph)
library(ggraph)
library(patchwork)
library(magrittr)
library(ralget)
library(ggforce)
library(raldag)
```

### Specify how nodes generate data and evaluate inputs
```{r message = FALSE, warning = FALSE}
a <- v("a", .f = d(~ rnorm(n = 1000, mean = rsum(.x), sd = .5)))
c <- v("c", .f = d(~ rnorm(n = 1000, mean = rsum(.x), sd = .5)))
x <- v("x", .f = d(~ rnorm(n = 1000, mean = rsum(.x), sd = .5)))
y <- v("y", .f = d(~ rnorm(n = 1000, mean = rsum(.x), sd = .5)))
m <- v("m", .f = d(~ rnorm(n = 1000, mean = rsum(.x), sd = .5)))
```

### Declare causal connections
```{r echo=TRUE, message=FALSE, warning=FALSE, include = TRUE, fig.height=3, fig.width=7}
g <-
 (a * b(1) + m * b(1)) * x +
 (c * b(1) + m * b(1)) * y +
 (a * b(1) + c * b(1)) * m

dag_plot(g)
```

### Generate data from DAG
```{r message = FALSE, warning = FALSE}
obs <- g %>% simulate(label = "Observational")
do0 <- g %>% ralget::do(a = -1) %>% simulate(label = "do(a = -1)",seed = 1)
do1 <- g %>% ralget::do(a =  1) %>% simulate(label = "do(a =  1)",seed = 1)
```

### Compare intervention distributions
```{r echo=TRUE, message=FALSE, warning=FALSE, include = TRUE, fig.height=5, fig.width=7}
bind_rows(obs, do0, do1) %>% plot_joint_distributions()
```